// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiULpNLsK_tlCfedOskX84vvZMrPuS3UE',
    appId: '1:213131208259:android:4e4381b646bba836a516f6',
    messagingSenderId: '213131208259',
    projectId: 'practice-4696e',
    storageBucket: 'practice-4696e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmO7t7yN_PAtk012kXqKQBKVZiA5eaPJI',
    appId: '1:213131208259:ios:d2bbf392aedf8c8fa516f6',
    messagingSenderId: '213131208259',
    projectId: 'practice-4696e',
    storageBucket: 'practice-4696e.appspot.com',
    iosClientId: '213131208259-a05scno5b0c8ckan57004733qisvo1et.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
